# Generated by Django 3.1.1 on 2020-09-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='body',
            new_name='comment',
        ),
    ]
