# Generated by Django 3.1.1 on 2020-09-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200912_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='comment_body',
        ),
    ]
